server:
  port: 8888
  servlet:
    context-path: /configservice

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AceNexus/configservice
          searchPaths: src/main/resources/configs
          clone-on-start: true

eureka:
  client: # 註冊到 eureka 註冊中心
    serviceUrl:
      defaultZone: http://${HOST:127.0.0.1}:8761/eurekaservice/eureka/

  instance:
    preferIpAddress: true