server:
  port: 8888

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AceNexus/configservice
          searchPaths: src/main/resources/{application}
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
