server:
  port: ${SERVER_PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AceNexus/configservice # 配置中心 Git 儲存庫 URI
          searchPaths: configs # 配置文件路徑
          clone-on-start: true # 啟動時同步倉庫
          default-label: main # 預設配置分支
          timeout: 5 # Git 倉庫請求超時機制
  security:
    user:
      name: ${SECURITY_USERNAME:admin} # 配置服務安全認證用戶名
      password: ${SECURITY_PASSWORD:password}  # 配置服務安全認證密碼