server:
  port: 8888
  servlet:
    context-path: /configservice

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AceNexus/configservice
          searchPaths: configs  # Git 倉庫中的相對路徑
          clone-on-start: true
          default-label: main  # 指定 Git 預設分支
          timeout: 5  # 設定 Git 請求超時秒數，防止連線問題