server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?useSSL=false&serverTimezone=UTC
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver