server:
  port: ${SERVER_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true # 使用 IP 地址而不是主機名
  client:
    register-with-eureka: true # 確保 Gateway 註冊到 Eureka
    fetch-registry: true # 允許 Gateway 獲取服務列表
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:3.107.210.167}:${EUREKA_SERVER_PORT:8761}/eureka/

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: accountservice
          uri: lb://accountservice
          predicates:
            - Path=/account/**  # 匹配所有 /account/ 開頭的請求
          filters:
            - StripPrefix=1
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
  security:
    user:
      name: ${SECURITY_USERNAME:admin}
      password: ${SECURITY_PASSWORD:password}