spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 啟用服務發現
          lower-case-service-id: true # 服務 ID 轉換為小寫
      routes:
        - id: gatewayservice
          uri: lb://gatewayservice
          predicates:
            - Path=/api/gateway/**
          filters:
            - StripPrefix=2 # 去掉 /api/gateway 前綴

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${SERVER_HOST:127.0.0.1}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:127.0.0.1}:${EUREKA_SERVER_PORT:8761}/eureka/ # Eureka 服務地址