LINE_CHANNEL_ACCESS_TOKEN: "dvqS3RJtN07Wqg6EXvWgnSdR3X+koAaL1GbDZWCnjHToBqw7IykTO2JNBjKi9UkOKuxI6Z90MdXCx/32j/NrcAbpx1RRIl+s2Yt6f0XuNP8WMuuXkfEcPyDXW4AV5ewQJtCG3jF+XRC08gP7zPDZvQdB04t89/1O/w1cDnyilFU="
LINE_CHANNEL_SECRET: "74f953573423fb9d4602b581a1af138d"
GROQ_API_KEY: "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"