LINE_CHANNEL_ACCESS_TOKEN: "3alsDGCaFprBkLH2OPSmz/Cnz/bsqzJ0AuYg8LTwBc7d7LTLrZ8R/W+OLQc2i4Gpr6SfNIRFNJBt00waEvjqrKetkQYxvC3yPBccXe4RJKwDX6zNNztP59AZsGyxfYWD5xswQ5KX4VxF0nnFl1tNXgdB04t89/1O/w1cDnyilFU="
LINE_CHANNEL_SECRET: "2b56c9f7bf07f7051336a29e94ce49af"
GROQ_API_KEY: "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"